Using alpha = 1.3004264056430888 beta = 1.0 rho = 0.05 phi = 0.05 tau0 = 1.0002287496346898 nAnts = 15 min_pheromone = 0.000720604168948716
Reading file: ./problems/rat783.tsp
Name: rat783
Best known: 8806
Dimension: 783
Distance matrix: 783x783
rat783:   0% [                                                            ]rat783:  12% [|||||||                                                     ]rat783:  24% [||||||||||||||                                              ]Best path found: 9627
Cost difference: 0.0932319
