Using alpha = 8.95666582 beta = 8.95666582 rho = 0.03455607276974871 phi = 0.018626021219141073 tau0 = 0.039682779748324695 nAnts = 10
Reading file: ./problems/rat783.tsp
Name: rat783
Best known: 8806
Dimension: 783
Distance matrix: 783x783
rat783:   0% [                                                            ]
[Iteration 0] Best cost: 11586

[Iteration 0] Best cost: 11369

[Iteration 0] Best cost: 11366

[Iteration 0] Best cost: 11258

[Iteration 0] Best cost: 11250
[Iteration 0] Best cost after local search: 9821
[Iteration 1] Best cost after local search: 9442

[Iteration 2] Best cost: 9437
[Iteration 2] Best cost after local search: 9384
[Iteration 3] Best cost after local search: 9366
[Iteration 4] Best cost after local search: 9364
[Iteration 5] Best cost after local search: 9364
rat783:   7% [||||                                                        ]rat783:  12% [|||||||                                                     ]rat783:  17% [||||||||||                                                  ]rat783:  22% [|||||||||||||                                               ]rat783:  27% [||||||||||||||||                                            ]rat783:  32% [|||||||||||||||||||                                         ]rat783:  37% [||||||||||||||||||||||                                      ]rat783:  43% [|||||||||||||||||||||||||                                   ]rat783:  48% [||||||||||||||||||||||||||||                                ]rat783:  53% [||||||||||||||||||||||||||||||||                            ]