(            4            2 )
(            2            2 )

(            1            2 )
(            2            2 )

Using alpha = 2.0090026247500825 beta = 0.0010681833317911504 rho = 0.7824308530729988 phi = 0.8409469695358073 tau0 = 3.3204841376786835e-05 nAnts = 15
Reading file: ./problems/lin318.tsp
Name: lin318
Best known: 42029
Dimension: 318
Distance matrix: 318x318
lin318:   0% [                                                            ]
[Iteration 0] Best cost: 313662

[Iteration 0] Best cost: 289316

[Iteration 0] Best cost: 288307
[Iteration 0] Best cost after local search: 55214
[Iteration 1] Best cost after local search: 46341
[Iteration 2] Best cost after local search: 44680
[Iteration 3] Best cost after local search: 44023
[Iteration 4] Best cost after local search: 43814
[Iteration 5] Best cost after local search: 43810
[Iteration 6] Best cost after local search: 43810
lin318:   1% [                                                            ]lin318:   2% [|                                                           ]lin318:   3% [||                                                          ]lin318:   4% [||                                                          ]lin318:   5% [|||                                                         ]lin318:   6% [|||                                                         ]lin318:   7% [||||                                                        ]lin318:   8% [||||                                                        ]lin318:   9% [|||||                                                       ]lin318:  10% [||||||                                                      ]lin318:  10% [||||||                                                      ]lin318:  11% [|||||||                                                     ]