Using alpha = 8.95666582 beta = 8.95666582 rho = 0.03455607276974871 phi = 0.018626021219141073 tau0 = 0.039682779748324695 nAnts = 10
Reading file: ./problems/fl1577.tsp
Name: fl1577
Best known: 22249
Dimension: 1577
Distance matrix: 1577x1577
fl1577:   0% [                                                            ]
[Iteration 0] Best cost: 32264

[Iteration 0] Best cost: 29919

[Iteration 0] Best cost: 29425

[Iteration 0] Best cost: 28836

[Iteration 0] Best cost: 28445

[Iteration 0] Best cost: 28028

[Iteration 0] Best cost: 28001
[Iteration 0] Best cost after local search: 24195
[Iteration 1] Best cost after local search: 23171
[Iteration 2] Best cost after local search: 23016

[Iteration 3] Best cost: 23008
[Iteration 3] Best cost after local search: 22990
[Iteration 4] Best cost after local search: 22981
[Iteration 5] Best cost after local search: 22967
[Iteration 6] Best cost after local search: 22954
[Iteration 7] Best cost after local search: 22954
