(            4            2 )
(            2            2 )

(            1            2 )
(            2            2 )

Using alpha = 2.0090026247500825 beta = 0.0010681833317911504 rho = 0.7824308530729988 phi = 0.8409469695358073 tau0 = 3.3204841376786835e-05 nAnts = 15
Reading file: ./problems/pr439.tsp
Name: pr439
Best known: 107217
Dimension: 439
Distance matrix: 439x439
pr439:   0% [                                                            ]
[Iteration 0] Best cost: 1040906

[Iteration 0] Best cost: 1002090

[Iteration 0] Best cost: 952697

[Iteration 0] Best cost: 943347

[Iteration 0] Best cost: 914269

[Iteration 0] Best cost: 824605
[Iteration 0] Best cost after local search: 145918
[Iteration 1] Best cost after local search: 121617
[Iteration 2] Best cost after local search: 116980
[Iteration 3] Best cost after local search: 114663
[Iteration 4] Best cost after local search: 113997
[Iteration 5] Best cost after local search: 113901
[Iteration 6] Best cost after local search: 113901
pr439:   3% [||                                                          ]pr439:   6% [|||                                                         ]pr439:   8% [||||                                                        ]pr439:  10% [||||||                                                      ]pr439:  12% [|||||||                                                     ]