(            4            2 )
(            2            2 )

(            1            2 )
(            2            2 )

Using alpha = 2.0090026247500825 beta = 0.0010681833317911504 rho = 0.7824308530729988 phi = 0.8409469695358073 tau0 = 3.3204841376786835e-05 nAnts = 15
Reading file: ./problems/pcb442.tsp
Name: pcb442
Best known: 50778
Dimension: 442
Distance matrix: 442x442
pcb442:   0% [                                                            ]
[Iteration 0] Best cost: 421810

[Iteration 0] Best cost: 399879

[Iteration 0] Best cost: 387507

[Iteration 0] Best cost: 376165

[Iteration 0] Best cost: 367623
[Iteration 0] Best cost after local search: 66219
[Iteration 1] Best cost after local search: 57309
[Iteration 2] Best cost after local search: 55731
[Iteration 3] Best cost after local search: 55672
[Iteration 4] Best cost after local search: 55672
pcb442:   3% [|                                                           ]pcb442:   5% [|||                                                         ]pcb442:   7% [||||                                                        ]pcb442:   9% [|||||                                                       ]pcb442:  11% [||||||                                                      ]