(            4            2 )
(            2            2 )

(            1            2 )
(            2            2 )

Using alpha = 2.0090026247500825 beta = 0.0010681833317911504 rho = 0.7824308530729988 phi = 0.8409469695358073 tau0 = 3.3204841376786835e-05 nAnts = 15
Reading file: ./problems/rat783.tsp
Name: rat783
Best known: 8806
Dimension: 783
Distance matrix: 783x783
rat783:   0% [                                                            ]
[Iteration 0] Best cost: 89658

[Iteration 0] Best cost: 89467

[Iteration 0] Best cost: 87049
[Iteration 0] Best cost after local search: 11658
[Iteration 1] Best cost after local search: 9893
[Iteration 2] Best cost after local search: 9582
[Iteration 3] Best cost after local search: 9510
[Iteration 4] Best cost after local search: 9508
[Iteration 5] Best cost after local search: 9508
