Using alpha = 8.95666582 beta = 8.95666582 rho = 0.03455607276974871 phi = 0.018626021219141073 tau0 = 0.039682779748324695 nAnts = 10
Reading file: ./problems/u1060.tsp
Name: u1060
Best known: 224094
Dimension: 1060
Distance matrix: 1060x1060
u1060:   0% [                                                            ]
[Iteration 0] Best cost: 309640

[Iteration 0] Best cost: 308177

[Iteration 0] Best cost: 307798

[Iteration 0] Best cost: 305016

[Iteration 0] Best cost: 298320

[Iteration 0] Best cost: 297490
[Iteration 0] Best cost after local search: 251764
[Iteration 1] Best cost after local search: 240124
[Iteration 2] Best cost after local search: 238437
[Iteration 3] Best cost after local search: 238050
[Iteration 4] Best cost after local search: 237963
[Iteration 5] Best cost after local search: 237963
u1060:  18% [|||||||||||                                                 ]u1060:  31% [|||||||||||||||||||                                         ]u1060:  44% [||||||||||||||||||||||||||                                  ]